name: Discord notification

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Police Bot
        DISCORD_AVATAR: https://paragonwiki.com/w/images//c/ca/PPD_Drone.jpg
      uses: Ilshidur/action-discord@master
