name: Discord notification

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Police Bot
        DISCORD_AVATAR: https://paragonwiki.com/w/images//c/ca/PPD_Drone.jpg
      uses: Ilshidur/action-discord@master
      
    - name: Discord Webhook Notify
      env:
        PR: ${{ github.event.pull_request }}
      uses: rjstone/discord-webhook-notify@v1.0.4
      with:
        # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        # Severity level - info, warn, or error
        severity: info # optional, default is error
        # Embed notification message. Use context expressions and environment variables to provide information. Default provides branch and user info.
        description: ${{ github.actor }} ${{ github.event_name }} # optional
        # Additional text after the notification message in case you want to retain the default message.
        details: ${{ github.event_name }} pull request \#${{PR.number}} (${{PR.title}}) # optional
        # Footer for the embed. Defaults to severity.
        footer: ${{ github.repository }} # optional
        # Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
        # text: # optional
        # Username to display in discord.
        username: Police Drone # optional
        # Notification color in the form poundsign rrggbb (hex). Default determined by severity.
        # color: # optional
        # URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
        avatarUrl: https://paragonwiki.com/w/images//c/ca/PPD_Drone.jpg # optional
